# Generated by Django 4.1 on 2022-10-28 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categary',
            new_name='category',
        ),
    ]
